; START OF PROGRAM
START:

; VARIABLES
A = 0
B = 1
D = '1'
E = '2'
F = 100
G = '0'
H = '`'
X = 10
Z = 96

TEMP = 0
TEMP_1 = 0
TEMP_2 = 0
TEMP_3 = 0
TEMP_4 = 0

KEYBOARD = 0

; Player variables
PLAYER_NAME_PRINT_LOW = 0
PLAYER_NAME_PRINT_HIGH = 100

PLAYER_NAME_END_LOW = 0
PLAYER_NAME_END_HIGH = 100

; MAIN
MAIN:
LIT 0A
PRINT "Welcome patient what's your name?"
LIT 0A
PRINT "Enter your name below."
LIT 0A

; PLAYER NAME INPUT LOOP
NAME_INPUT_LOOP:
STK KEYBOARD
LDT KEYBOARD
LDA KEYBOARD
CMP A
JPE NAME_INPUT_LOOP
CMP Z
JPE MAIN
CMP X
JPE GAME_LOOP
LD0 PLAYER_NAME_END_LOW
LD1 PLAYER_NAME_END_HIGH
STI 
LDA PLAYER_NAME_END_LOW
ADD B
STA PLAYER_NAME_END_LOW
LIA 00
STA KEYBOARD
JMP NAME_INPUT_LOOP

; MAIN GAME LOOP
GAME_LOOP:
LDA PLAYER_NAME_END_LOW
SUB B
STA PLAYER_NAME_END_LOW

START_GAME:
LIT 0A
PRINT "Welcome Patient"

CONTINUE_GAME:
LIT 0A
PRINT "Medical Triage Station"
LIT 0A
PRINT "Let's determine how urgent your symptoms are."

; START TRIAGE TREE
QUESTION_C1:
LIT 0A
PRINT "Are you experiencing any of the following?"
LIT 0A
PRINT "1. Severe chest pain or difficulty breathing"
LIT 0A
PRINT "2. No"

QUESTION_C1_SELECTION_LOOP:
STK KEYBOARD
LDA KEYBOARD
CMP A
JPE QUESTION_C1_SELECTION_LOOP
CMP D
JPE RED_TAG
CMP E
JPE QUESTION_C2
JMP QUESTION_C1_SELECTION_LOOP

QUESTION_C2:
LIT 0A
PRINT "Sudden weakness or numbness on one side?"
LIT 0A
PRINT "1. Yes"
LIT 0A
PRINT "2. No"

QUESTION_C2_SELECTION_LOOP:
STK KEYBOARD
LDA KEYBOARD
CMP A
JPE QUESTION_C2_SELECTION_LOOP
CMP D
JPE RED_TAG
CMP E
JPE QUESTION_C3
JMP QUESTION_C2_SELECTION_LOOP

QUESTION_C3:
LIT 0A
PRINT "Severe bleeding or major trauma?"
LIT 0A
PRINT "1. Yes"
LIT 0A
PRINT "2. No"

QUESTION_C3_SELECTION_LOOP:
STK KEYBOARD
LDA KEYBOARD
CMP A
JPE QUESTION_C3_SELECTION_LOOP
CMP D
JPE RED_TAG
CMP E
JPE QUESTION_C4
JMP QUESTION_C3_SELECTION_LOOP

QUESTION_C4:
LIT 0A
PRINT "Loss of consciousness or seizure (not diagnosed)?"
LIT 0A
PRINT "1. Yes"
LIT 0A
PRINT "2. No"

QUESTION_C4_SELECTION_LOOP:
STK KEYBOARD
LDA KEYBOARD
CMP A
JPE QUESTION_C4_SELECTION_LOOP
CMP D
JPE RED_TAG
CMP E
JPE QUESTION_C5
JMP QUESTION_C4_SELECTION_LOOP

QUESTION_C5:
LIT 0A
PRINT "Sudden severe headache (worst ever)?"
LIT 0A
PRINT "1. Yes"
LIT 0A
PRINT "2. No"

QUESTION_C5_SELECTION_LOOP:
STK KEYBOARD
LDA KEYBOARD
CMP A
JPE QUESTION_C5_SELECTION_LOOP
CMP D
JPE RED_TAG
CMP E
JPE QUESTION_C6
JMP QUESTION_C5_SELECTION_LOOP

QUESTION_C6:
LIT 0A
PRINT "Signs of anaphylaxis (swelling, rash, etc)?"
LIT 0A
PRINT "1. Yes"
LIT 0A
PRINT "2. No"

QUESTION_C6_SELECTION_LOOP:
STK KEYBOARD
LDA KEYBOARD
CMP A
JPE QUESTION_C6_SELECTION_LOOP
CMP D
JPE RED_TAG
CMP E
JPE QUESTION_C7
JMP QUESTION_C6_SELECTION_LOOP

QUESTION_C7:
LIT 0A
PRINT "Suspected poisoning or overdose?"
LIT 0A
PRINT "1. Yes"
LIT 0A
PRINT "2. No"

QUESTION_C7_SELECTION_LOOP:
STK KEYBOARD
LDA KEYBOARD
CMP A
JPE QUESTION_C7_SELECTION_LOOP
CMP D
JPE RED_TAG
CMP E
JPE QUESTION_C8
JMP QUESTION_C7_SELECTION_LOOP

QUESTION_C8:
LIT 0A
PRINT "High fever with stiff neck or light sensitivity?"
LIT 0A
PRINT "1. Yes"
LIT 0A
PRINT "2. No"

QUESTION_C8_SELECTION_LOOP:
STK KEYBOARD
LDA KEYBOARD
CMP A
JPE QUESTION_C8_SELECTION_LOOP
CMP D
JPE RED_TAG
CMP E
JPE QUESTION_D1
JMP QUESTION_C8_SELECTION_LOOP

; ORANGE SYMPTOMS
QUESTION_D1:
LIT 0A
PRINT "Moderate to severe worsening pain?"
LIT 0A
PRINT "1. Yes"
LIT 0A
PRINT "2. No"

QUESTION_D1_SELECTION_LOOP:
STK KEYBOARD
LDA KEYBOARD
CMP A
JPE QUESTION_D1_SELECTION_LOOP
CMP D
JPE ORANGE_TAG
CMP E
JPE QUESTION_D2
JMP QUESTION_D1_SELECTION_LOOP

QUESTION_D2:
LIT 0A
PRINT "Persistent vomiting or dehydration?"
LIT 0A
PRINT "1. Yes"
LIT 0A
PRINT "2. No"

QUESTION_D2_SELECTION_LOOP:
STK KEYBOARD
LDA KEYBOARD
CMP A
JPE QUESTION_D2_SELECTION_LOOP
CMP D
JPE ORANGE_TAG
CMP E
JPE QUESTION_D3
JMP QUESTION_D2_SELECTION_LOOP

QUESTION_D3:
LIT 0A
PRINT "Fever with major discomfort not relieved at home?"
LIT 0A
PRINT "1. Yes"
LIT 0A
PRINT "2. No"

QUESTION_D3_SELECTION_LOOP:
STK KEYBOARD
LDA KEYBOARD
CMP A
JPE QUESTION_D3_SELECTION_LOOP
CMP D
JPE ORANGE_TAG
CMP E
JPE QUESTION_D4
JMP QUESTION_D3_SELECTION_LOOP

QUESTION_D4:
LIT 0A
PRINT "New or worsening abdominal pain?"
LIT 0A
PRINT "1. Yes"
LIT 0A
PRINT "2. No"

QUESTION_D4_SELECTION_LOOP:
STK KEYBOARD
LDA KEYBOARD
CMP A
JPE QUESTION_D4_SELECTION_LOOP
CMP D
JPE ORANGE_TAG
CMP E
JPE QUESTION_D5
JMP QUESTION_D4_SELECTION_LOOP

QUESTION_D5:
LIT 0A
PRINT "Persistent cough with mild shortness of breath?"
LIT 0A
PRINT "1. Yes"
LIT 0A
PRINT "2. No"

QUESTION_D5_SELECTION_LOOP:
STK KEYBOARD
LDA KEYBOARD
CMP A
JPE QUESTION_D5_SELECTION_LOOP
CMP D
JPE ORANGE_TAG
CMP E
JPE QUESTION_D6
JMP QUESTION_D5_SELECTION_LOOP

QUESTION_D6:
LIT 0A
PRINT "Possible broken bone?"
LIT 0A
PRINT "1. Yes"
LIT 0A
PRINT "2. No"

QUESTION_D6_SELECTION_LOOP:
STK KEYBOARD
LDA KEYBOARD
CMP A
JPE QUESTION_D6_SELECTION_LOOP
CMP D
JPE ORANGE_TAG
CMP E
JPE QUESTION_D7
JMP QUESTION_D6_SELECTION_LOOP

QUESTION_D7:
LIT 0A
PRINT "Signs of infection with fever (swelling/redness)?"
LIT 0A
PRINT "1. Yes"
LIT 0A
PRINT "2. No"

QUESTION_D7_SELECTION_LOOP:
STK KEYBOARD
LDA KEYBOARD
CMP A
JPE QUESTION_D7_SELECTION_LOOP
CMP D
JPE ORANGE_TAG
CMP E
JPE QUESTION_E1
JMP QUESTION_D7_SELECTION_LOOP

; GREEN SYMPTOMS
QUESTION_E1:
LIT 0A
PRINT "Common cold or mild flu symptoms?"
LIT 0A
PRINT "1. Yes"
LIT 0A
PRINT "2. No"

QUESTION_E1_SELECTION_LOOP:
STK KEYBOARD
LDA KEYBOARD
CMP A
JPE QUESTION_E1_SELECTION_LOOP
CMP D
JPE GREEN_TAG
CMP E
JPE QUESTION_E2
JMP QUESTION_E1_SELECTION_LOOP

QUESTION_E2:
LIT 0A
PRINT "Minor cuts or scrapes?"
LIT 0A
PRINT "1. Yes"
LIT 0A
PRINT "2. No"

QUESTION_E2_SELECTION_LOOP:
STK KEYBOARD
LDA KEYBOARD
CMP A
JPE QUESTION_E2_SELECTION_LOOP
CMP D
JPE GREEN_TAG
CMP E
JPE QUESTION_E3
JMP QUESTION_E2_SELECTION_LOOP

QUESTION_E3:
LIT 0A
PRINT "Mild aches or pains improving with rest?"
LIT 0A
PRINT "1. Yes"
LIT 0A
PRINT "2. No"

QUESTION_E3_SELECTION_LOOP:
STK KEYBOARD
LDA KEYBOARD
CMP A
JPE QUESTION_E3_SELECTION_LOOP
CMP D
JPE GREEN_TAG
CMP E
JPE QUESTION_E4
JMP QUESTION_E3_SELECTION_LOOP

QUESTION_E4:
LIT 0A
PRINT "Routine prescription refill?"
LIT 0A
PRINT "1. Yes"
LIT 0A
PRINT "2. No"

QUESTION_E4_SELECTION_LOOP:
STK KEYBOARD
LDA KEYBOARD
CMP A
JPE QUESTION_E4_SELECTION_LOOP
CMP D
JPE GREEN_TAG
CMP E
JPE QUESTION_E5
JMP QUESTION_E4_SELECTION_LOOP

QUESTION_E5:
LIT 0A
PRINT "1. Yes"
LIT 0A
PRINT "2. No"

QUESTION_E5_SELECTION_LOOP:
STK KEYBOARD
LDA KEYBOARD
CMP A
JPE QUESTION_E5_SELECTION_LOOP
CMP D
JPE GREEN_TAG
CMP E
JPE UNCATEGORIZED
JMP QUESTION_E5_SELECTION_LOOP

; RESULTS
RED_TAG:
LIT 0A
PRINT "You are experiencing a RED (Emergency) level condition."
LIT 0A
PRINT "Please call emergency services or go to the ER immediately."
JMP GAME_OVER

ORANGE_TAG:
LIT 0A
PRINT "You are experiencing an ORANGE (Priority) condition."
LIT 0A
PRINT "Please seek urgent medical attention as soon as possible."
JMP GAME_OVER

GREEN_TAG:
LIT 0A
PRINT "You are experiencing a GREEN (NONURGENT) condition."
LIT 0A
PRINT "Please rest and monitor your symptoms. Follow up with a provider if needed."
JMP GAME_OVER

UNCATEGORIZED:
LIT 0A
PRINT "We couldn't categorize your symptoms."
LIT 0A
PRINT "If you're unsure, please seek medical attention or call a nurse line."
JMP GAME_OVER

; GAME OVER
GAME_OVER:
LIT 0A
PRINT "Done for this patient"
LIT 0A
PRINT "Press enter to assess next patient."

GAME_OVER_SELECTION_LOOP:
STK KEYBOARD
LDA KEYBOARD
CMP A
JPE GAME_OVER_SELECTION_LOOP
CMP X
JPE START
JMP GAME_OVER_SELECTION_LOOP

CLEAR_VARIABLES:
LIA 00
STA TEMP_4
STA TEMP_3
STA TEMP_2
STA TEMP_1
RET

; Split number into digits for printing
SPLIT_NUMBER:
MINUS_100:
LDA TEMP_4
CMP F
JPL MINUS_10
SUB F
STA TEMP_4
LDA TEMP_3
ADD B
STA TEMP_3
CMP TEMP_4
JPL MINUS_100
JPE MINUS_100

MINUS_10:
LDA TEMP_4
CMP X
JPL RETURN
SUB X
STA TEMP_4
LDA TEMP_2
ADD B
STA TEMP_2
CMP TEMP_4
JPL MINUS_10
JPE MINUS_10
RET

PRINT_SPLIT_NUMBER:
LDA TEMP_4
ADD G
STA TEMP_1
LDA TEMP_2
ADD G
STA TEMP_2
LDA TEMP_3
ADD G
STA TEMP_3
LDT TEMP_3
LDT TEMP_2
LDT TEMP_1
JCAL CLEAR_VARIABLES
RET

RETURN:
RET
